name: Helm Values Merge
author: gpuliyar
description: >
  Github custom action to merge Helm Values with custom configurations
branding:
  icon: code
  color: orange
inputs:
  repository:
    description: The application repository name
    required: true
  chart-tag:
    description: The application package chart tag
    required: true
outputs:
  values-file:
    description: Final merged Helm Chart values.yml file
runs:
  using: node16
  main: dist/index.js
